# Generated by Django 5.2.5 on 2025-08-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('companies', '0002_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Kompaniya'),
        ),
    ]
