# Generated by Django 5.2.5 on 2025-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Omborda bormi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Uzunlik x Kenglik x Balandlik', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Og'irligi (kg)", max_digits=8, null=True),
        ),
    ]
