# Generated by Django 5.2.5 on 2025-08-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_created_at_alter_company_updated_at'),
        ('products', '0002_alter_product_options_remove_product_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Kompaniya'),
        ),
    ]
